production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8080
    path: /solr/sunspot
    log_level: DEBUG

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING